#ifndef NEURON_HPP
#define NEURON_HPP
#include "constant.h"
#include <vector> 
using namespace std;

/**
 * ... The Neuron Class ...
 */

class Neuron {
	
private : 

	/**
	 * ... General Attributes ...
	 */
	
	/**< pot_ = membrane potential in mV */
	double pot_;    
	
	/**< clock_ = the internal clock of the neuron */
	int clock_;    
	
	/**< spikes_ = vector of all spikes sent by the neuron. 
	 * Each case correspond to the time when the spike occured */
	vector<int> spikes_;
	 
	/**< n_spikes_ = number of spikes sent by a  */
	int n_spikes_;    
	
	/**< buffer_ = vector that enable the neuron to receive a spike 
	 * from anoter neuron after a delay */
	vector<double> buffer_;    
	 
	/**< spike_ = true if the neuron is spiking, false if he is not 
	 * for a Gtest */
	bool spike_;    
	
	/**< e_= true if the neuron is exitatory, false if he is inhibitory */
	bool e_;    
	
	/**< received_connections_ = The values in the cases of this vector 
	 * are the index of the neurons (where they are in neurons_(cf network))
	 * that are connected to the current neurons in the following way : 
	 * the current neuron receives potential from them */ 
	vector<int> received_connections_;    
	
	/**< sent_connections_ = The values in the cases of this vector
	 *  are the index of the neurons (where they are in neurons_(cf network)) 
	 * that are connected to the current neurons in the following way : 
	 * the current neuron sends potential to them */    
	vector<int> sent_connections_;    
	 
	/**< received_spikes_ = vector that contains the time (after the delay of each each spike received by the neuron */
	vector<int> received_spikes_;    									//for the TEST 6 I have decided to skip
	
	

	
public :

	/*****************************************************/

	/**
	 * ... Constructor ...
	 */
	 
	Neuron();
	
	
	/*****************************************************/
	 
	/**
	 * ... Getters ...
	 */
	 
	/** @return pot_ */
	double getPot() const;    
	
	/** @return spike_ */
	bool getSpike() const;    
	
	/** @return spikes_ */ 
	vector<int> getSpikes() const;    
	
	/** 
	 * @param a : the index of the spike we are insterested in
	 * @return the time of given spike */
	double getSpikeTime(size_t a) const;    
	
	/** @return the number of spike */
	int getSpikesN() const;    
	
	/** @return clock_ */
	int getClock() const;    
	
	/** @return the incoming potential J 
	 * from another neuron, sent at a given time, 
	 * and received by the neuron after the delay */
	double bufferAfterDelay();    
	 
	/** @return e_ */
	bool getE();    
	
	/** @return received_connections_ */
	vector<int> getReceivedConnections();    
	
	/** @return sent_connections_ */
	vector<int> getSentConnections();    
	
	/** @return received_spikes_ */
	vector<int> getReceivedSpikes();    
	
	
	/*****************************************************/
	
	/**
	 * ... Setters ...
	 */
	
	/** @param pot : to set the potentiel */ 
	void setPot(double pot);
	
	/** @param e : to set the buffer 
	 * depending on the state (e)
	 * of the sending neuron */
	void setBuffer(bool e);
	
	/** @param b : to set the state of the neuron */ 
	void setE(bool b);
	
	
	/*****************************************************/
	
	/**
	 * ... Updates ...
	 */
	
	/** @param noise : to update the potential of the neuron 
	 * with a random noise, generated by external neurons 
	 * @return true if the neuron is spiking */ 
	bool update (double I, double noise);
	
	/** 
	 * @param I : the external current 
	 * the input for a neuron at the begining of the project 
	 * @param J : to add the inconming potential stored
	 * in the buffer in the differential equation 
	 * which calculate the potenial, taking in account
	 * the previous potential of the neuron 
	 * @param noise : same paramater of the update method
	 * because updatePot is called in update */ 
	void updatePot (double I, double J, double noise);
	
	/** to update the clock
	 * going in a new step */
	void updateClock();
	 
	 
	/*****************************************************/
	
	/** 
	 * ... Adders ... 
	 */

	/** @param c : to connect the neuron 
	 * with the neuron at index c
	 * (where they are in neurons_(cf network))
	 * by adding the this index in a case of 
	 * the vector received_connections_
	 * so that this neuron will be able 
	 * to send spike to the current neuron */
	void addReceivedConnection(int c);
	 
	/** @param c : to connect the neuron 
	 * with the neuron at index c
	 * (where they are in neurons_(cf network))
	 * by adding the this index in a case of 
	 * the vector sent_connections_
	 * so that that the current neuron will 
	 * be able to send spike the neuron of index c */
	void addSentConnection(int c);
	 
	/** @param t : to reveice a spike at (t+D)
	 * which is send at time t
	 * ONLY FOR A GTEST */
	void addReceivedSpike(int t);
	 
	 
	/*****************************************************/
	 
	 
	 
	
};

#endif	           

